const fill=document.querySelector('.tp-water'),system=document.querySelector('.tp-system');if(fill&&system&&!matchMedia('(prefers-reduced-motion: reduce)').matches){let pending=false;const update=()=>{const rect=system.getBoundingClientRect();const progress=Math.max(0,Math.min(1,(innerHeight*.4-rect.top)/Math.max(1,rect.height-innerHeight*.6)));fill.style.height=(progress*100)+'%';pending=false;};addEventListener('scroll',()=>{if(!pending){pending=true;requestAnimationFrame(update);}},{passive:true});addEventListener('resize',update);document.querySelectorAll('details').forEach(item=>item.addEventListener('toggle',update));update();}const branches=document.querySelector('.tp-branches');if(branches){const draw=()=>{const frame=branches.getBoundingClientRect(),riser=document.querySelector('.tp-riser').getBoundingClientRect();const x=riser.left+riser.width/2-frame.left;let segments=[];const rows=new Map();document.querySelectorAll('.tp-service-grid article').forEach(card=>{const box=card.getBoundingClientRect();const y=Math.round(box.top+box.height/2-frame.top);rows.set(y,Math.max(rows.get(y)||0,box.left+12-frame.left));});rows.forEach((end,y)=>segments.push('M'+x+' '+y+'H'+end));branches.setAttribute('viewBox','0 0 '+frame.width+' '+frame.height);branches.querySelectorAll('path').forEach(path=>path.setAttribute('d',segments.join(' ')));};addEventListener('resize',draw);document.fonts.ready.then(draw);new ResizeObserver(draw).observe(document.querySelector('.tp-service-grid'));draw();}
const requestForm=document.querySelector('.tp-form');
if(requestForm){
 requestForm.hidden=false;
 const draft=requestForm.querySelector('.tp-draft'),review=requestForm.querySelector('.tp-message-review'),preview=requestForm.querySelector('.tp-preview'),status=requestForm.querySelector('.tp-status'),copy=requestForm.querySelector('.tp-copy');
 const invalidate=()=>{draft.hidden=true;draft.removeAttribute('href');review.hidden=true;status.textContent='';copy.textContent='Copy message';};
 requestForm.addEventListener('input',invalidate);requestForm.addEventListener('change',invalidate);
 document.querySelectorAll('[data-service]').forEach(link=>link.addEventListener('click',()=>{invalidate();requestForm.elements.service.value=link.dataset.service;status.textContent=link.dataset.service+' selected. Add the details below.';}));
 requestForm.addEventListener('submit',event=>{event.preventDefault();if(!requestForm.reportValidity())return;const data=new FormData(requestForm);const lines=["Service question for Tom's Plumbing & Heating Services",'Name: '+data.get('name'),'Contact: '+data.get('reach'),'Neighborhood: '+(data.get('place')||'Not specified'),'Service: '+data.get('service')];if(data.has('unit'))lines.push('Unit type: '+data.get('unit'));lines.push('Issue: '+data.get('issue'));const message=lines.join('\n');preview.value=message;draft.href='sms:'+"+19298883311"+(/iPhone|iPad|iPod/.test(navigator.userAgent)?'&':'?')+'body='+encodeURIComponent(message);draft.hidden=false;review.hidden=false;status.textContent='Message prepared. Review it, then open your text app or copy it. Nothing has been sent.';preview.focus({preventScroll:true});});
 copy.addEventListener('click',async()=>{try{if(!navigator.clipboard)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(preview.value);copy.textContent='Message copied';status.textContent='Copied. Paste it into your preferred app and send it when ready.';}catch(error){preview.focus();preview.select();status.textContent='Message selected. Use your device’s Copy command, then paste it into your preferred app.';}});
 const unitButtons=document.querySelectorAll('[data-unit]');unitButtons.forEach(button=>button.addEventListener('click',()=>{invalidate();unitButtons.forEach(item=>item.setAttribute('aria-pressed',String(item===button)));requestForm.elements.unit.value=button.dataset.unit;document.querySelector('.sc-unit-answer').textContent=button.dataset.unit+' selected. This choice is added to your text draft.';}));
}
const photoDialog=document.querySelector('.tp-photo-dialog');
if(photoDialog&&typeof photoDialog.showModal==='function'){
 let opener=null;const picture=new Image(),caption=photoDialog.querySelector('p');
 document.querySelectorAll('.tp-gallery figure').forEach(figure=>{const photo=figure.querySelector('img');if(!photo)return;const note=figure.querySelector('figcaption');const label=note?note.innerText:photo.alt;const button=document.createElement('button');button.type='button';button.className='tp-photo-open';button.setAttribute('aria-label','View photo: '+label);photo.before(button);button.append(photo);const hint=document.createElement('span');hint.setAttribute('aria-hidden','true');hint.textContent='View photo ↗';button.append(hint);button.addEventListener('click',()=>{opener=button;picture.src=photo.src;picture.alt=photo.alt;picture.width=photo.naturalWidth;picture.height=photo.naturalHeight;caption.textContent=label;caption.before(picture);photoDialog.showModal();});});
 const closeButton=photoDialog.querySelector('button'),close=()=>photoDialog.close();closeButton.addEventListener('click',close);photoDialog.addEventListener('keydown',event=>{if(event.key==='Tab'){event.preventDefault();closeButton.focus();}});photoDialog.addEventListener('click',event=>{if(event.target===photoDialog){const r=photoDialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)close();}});photoDialog.addEventListener('close',()=>{if(opener)opener.focus({preventScroll:true});});
}
