
const requestForm=document.querySelector('.shop-ticket');
if(requestForm){
 requestForm.hidden=false;
 const draft=requestForm.querySelector('.shop-draft'),review=requestForm.querySelector('.shop-message-review'),preview=requestForm.querySelector('.shop-preview'),status=requestForm.querySelector('.shop-status'),copy=requestForm.querySelector('.shop-copy');
 const invalidate=()=>{draft.hidden=true;draft.removeAttribute('href');review.hidden=true;status.textContent='';copy.textContent='Copy message';};
 requestForm.addEventListener('input',invalidate);requestForm.addEventListener('change',invalidate);
 document.querySelectorAll('[data-service]').forEach(link=>link.addEventListener('click',()=>{invalidate();requestForm.elements.service.value=link.dataset.service;status.textContent=link.dataset.service+' selected. Add the details below.';}));
 requestForm.addEventListener('submit',event=>{event.preventDefault();if(!requestForm.reportValidity())return;const data=new FormData(requestForm);const lines=["Service question for Elias Mechanical Services",'Name: '+data.get('name'),'Contact: '+data.get('reach'),'Neighborhood: '+(data.get('place')||'Not specified'),'Service: '+data.get('service')];if(data.has('unit'))lines.push('Unit type: '+data.get('unit'));lines.push('Issue: '+data.get('issue'));const message=lines.join('\n');preview.value=message;draft.href='mailto:'+"eliasmechanicalservice@gmail.com"+'?subject='+encodeURIComponent("Service question for Elias Mechanical Services")+'&body='+encodeURIComponent(message);draft.hidden=false;review.hidden=false;status.textContent='Message prepared. Review it, then open your email app or copy it. Nothing has been sent.';preview.focus({preventScroll:true});});
 copy.addEventListener('click',async()=>{try{if(!navigator.clipboard)throw new Error('Clipboard unavailable');await navigator.clipboard.writeText(preview.value);copy.textContent='Message copied';status.textContent='Copied. Paste it into your preferred app and send it when ready.';}catch(error){preview.focus();preview.select();status.textContent='Message selected. Use your device’s Copy command, then paste it into your preferred app.';}});
 const unitButtons=document.querySelectorAll('[data-unit]');unitButtons.forEach(button=>button.addEventListener('click',()=>{invalidate();unitButtons.forEach(item=>item.setAttribute('aria-pressed',String(item===button)));requestForm.elements.unit.value=button.dataset.unit;document.querySelector('.sc-unit-answer').textContent=button.dataset.unit+' selected. This choice is added to your text draft.';}));
}
const photoDialog=document.querySelector('.shop-photo-dialog');
if(photoDialog&&typeof photoDialog.showModal==='function'){
 let opener=null;const picture=new Image(),caption=photoDialog.querySelector('p');
 document.querySelectorAll('.shop-gallery figure').forEach(figure=>{const photo=figure.querySelector('img');if(!photo)return;const note=figure.querySelector('figcaption');const label=note?note.innerText:photo.alt;const button=document.createElement('button');button.type='button';button.className='shop-photo-open';button.setAttribute('aria-label','View photo: '+label);photo.before(button);button.append(photo);const hint=document.createElement('span');hint.setAttribute('aria-hidden','true');hint.textContent='View photo ↗';button.append(hint);button.addEventListener('click',()=>{opener=button;picture.src=photo.src;picture.alt=photo.alt;picture.width=photo.naturalWidth;picture.height=photo.naturalHeight;caption.textContent=label;caption.before(picture);photoDialog.showModal();});});
 const closeButton=photoDialog.querySelector('button'),close=()=>photoDialog.close();closeButton.addEventListener('click',close);photoDialog.addEventListener('keydown',event=>{if(event.key==='Tab'){event.preventDefault();closeButton.focus();}});photoDialog.addEventListener('click',event=>{if(event.target===photoDialog){const r=photoDialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)close();}});photoDialog.addEventListener('close',()=>{if(opener)opener.focus({preventScroll:true});});
}
